// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsDo78CsmAg6A7Fv4P0pXx56NWATkFIhE',
    appId: '1:190321359551:web:723f956de091730959e40a',
    messagingSenderId: '190321359551',
    projectId: 'final-year-project-b2150',
    authDomain: 'final-year-project-b2150.firebaseapp.com',
    storageBucket: 'final-year-project-b2150.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp380ACaZQuOY83Jbi0UGyfnFpPxEY6CA',
    appId: '1:190321359551:android:e4b7bcaae6da92bc59e40a',
    messagingSenderId: '190321359551',
    projectId: 'final-year-project-b2150',
    storageBucket: 'final-year-project-b2150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLy3vLR439GzHneC2D2BZWc7gCGrTj4zo',
    appId: '1:190321359551:ios:590fff7aba43368059e40a',
    messagingSenderId: '190321359551',
    projectId: 'final-year-project-b2150',
    storageBucket: 'final-year-project-b2150.appspot.com',
    androidClientId: '190321359551-0euuohlnu94s0qmc0lvref9m6heu8tql.apps.googleusercontent.com',
    iosClientId: '190321359551-pv3mbvcff4tso4ffofhifc6eok15lv1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypAdmin',
  );
}
